### ISSUE TITLE
Scrolling Issue in Message Tab

### ISSUE THREAD

**Issue by clayop** [adcpm/busy#302] opened 2017-02-02 09:31 UTC
I cannot scroll to the end of my list.

**Comment by adcpm** [comment] 2017-02-02 09:56
@clayop Are you referring to the contact list on the sidebar?

**Comment by tibonova** [comment] 2017-02-04 08:22
@adcpm It is a chat (channel) issue, for example [here](https://busy.org/messages/life).

**Comment by clayop** [comment] 2017-02-04 08:43
@adcpm maybe rigjt. Sidetab on the left

**Comment by tibonova** [comment] 2017-02-04 08:55
@clayop OK, I'll open a new issue for that then. 

Adding to this one, it's maybe a duplicate of #301

**Comment by adcpm** [comment] 2017-02-04 08:56
Yes i'm closing this one it's a duplicate thx @tibonova @clayop

**Closed by adcpm** 2017-02-04 08:56 UTC
